# 配置端口信息
server:
  port: 8080

# 配置项目信息
spring:
  application:
    name: sport
  profiles:
    active: dev

#  mvc:
#    # 解决Swagger2和springboot版本不同产生的问题
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  servlet:
#    multipart:
#      max-file-size: 10MB #上传单个文件最大限制
#      max-request-size: 10MB #上传多个文件最大限制
#  # 配置Mysql数据源
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sport_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#  #redis 配置
#  redis:
#    # 配置主机
#    host: 127.0.1
#    # 配置使用的数据库
#    database: 0
#    # 指定端口
#    port: 6379
#  # 邮件配置
#  mail:
#    # smtp服务主机 QQ:smtp.qq.com
#    host: smtp.qq.com
#    # 服务协议
#    protocol: smtp
#    # 设置编码集
#    default-encoding: UTF-8
#    # 允许测试连接
#    test-connection: true
#    # 设置发件人
#    username: 1744881633@qq.com
#    # 设置授权码
#    password: yjrjoxskxddhcdee

mybatis:
  # mapper接口找的XML文件
  mapper-locations: classpath:mapper/*.xml
#  # 实体类
#  type-aliases-package: com.wujiajun.entity
  # mybatis 内置的配置
  configuration:
    # sql 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: wujiajun123
  # jwt过期时间（秒）
  expiration: 18000
  # token头部
  tokenHead: 'Bearer'

# 配置七牛云
qiniu:
  accessKey: msmLHZun3XnkbeTKDdFVTAqdUxfcAoB1_2jQrIbD
  secretKey: ndngeOhE5-EhM-Bg3XzhTNXpRrP8PNOThaobgzbq
  bucket: sportwjj

# 微信小程序
mini:
  # 密钥
  appid: wx545788977c98e237
  secret: e2bdc96bea48aa0213a44ed9fcfd6129